version: '3'

services:

  magazine:
    build: .
    image: magazine
    container_name: magazine
    restart: always
    environment:
      APP_DEBUG: 'false'
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: magazine
      DB_USERNAME: root
      DB_PASSWORD: root@hsj@2371
      APP_URL: https://revista.hsj.ce.gov.br
    volumes:
      - ./magazine/public:/app/public
    ports:
      - 8177:8182
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@hsj@2371
      MYSQL_DATABASE: magazine
    ports:
      - 3306:3306
    volumes:
      - mysqldrive:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8190:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root@hsj@2371
    depends_on:
      - db
networks:
  default:
volumes: 
  mysqldrive: