version: '3'

services:

  magazine:
    build: .
    image: magazine
    container_name: magazine
    restart: always
    environment:
      APP_DEBUG: 'true'
      DB_CONNECTION: mysql
      DB_HOST: 10.14.1.21
      DB_PORT: 3306
      DB_DATABASE: magazine
      DB_USERNAME: root
      DB_PASSWORD: root@hsj@2371
      APP_URL: https://revista.hsj.ce.gov.br
    volumes:
      - ./magazine/public:/app/public
    ports:
      - 8177:8181
  
networks:
  default:
volumes: 
  mysqldrive: